title: My Website
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  My personal website and blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kucukogluberk.github.io" # the base hostname & protocol for your site
theme: "minima"

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Google Analytics
google_analytics: UA-XXXXXXXX-X

# To enable image excerpts, configure these image paths:
# header:
#   overlay_image: /assets/images/mm-home-page-feature.jpg

# Navigation links
# Set the URLs to the pages you created above
nav:
  - text: "Home"
    url: /
  - text: "About"
    url: /about/

